DROP DATABASE IF EXISTS contact_manager;
CREATE DATABASE contact_manager DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE contact_manager;

CREATE TABLE clients (
  id INT PRIMARY KEY AUTO_INCREMENT,
  clientId VARCHAR(255) NOT NULL UNIQUE,
  apiKey VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  quotaMax INT NOT NULL DEFAULT 1000,
  messagesSent INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) UNIQUE NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
